repos:
  - repo: local
    hooks:
      - id: glance-update
        name: Update glance documentation
        entry: bash -c 'glance ./ >/dev/null 2>&1 &'
        language: system
        always_run: true
        pass_filenames: false
        stages: [pre-commit]